### ISSUE TITLE
Document how to set up a free BigQuery account

### ISSUE THREAD

**Issue by philgerardsoto** [OSSPhilippines/personal-well-being-dashboard#18]

**Comment by philgerardsoto** [comment]
Doesn't need to be fancy. We can link to existing documentation from Google itself.

**Comment by gongahkia** [comment]
hi @philgerardsoto please assign this issue to me

**Comment by philgerardsoto** [comment]
Hi. Yes @gongahkia for now let's place it there.

**Comment by philgerardsoto** [comment]
Thanks @gongahkia will review later, then merge if all good.
