### ISSUE TITLE
Given a pandas dataframe, load to BigQuery

### ISSUE THREAD

**Issue by philgerardsoto** [OSSPhilippines/personal-well-being-dashboard#7]

**Comment by jenisesc** [comment]
Id like to work on this!

**Comment by philgerardsoto** [comment]
Sure. Thank you! There are more loading tasks after this.

**Comment by sairilseb-me** [comment]
Hi @philgerardsoto I would like to also take part in this task. @jenisesc if that is okay with you? We will collaborate on this task :)

**Comment by philgerardsoto** [comment]
Sure! @joemarkyangag also started some work on this so kindly see his linked open PR.

**Comment by philgerardsoto** [comment]
Closing this as we'll be using DuckDB instead.
